---
- name: LVM manager for the new disk
  hosts: nodes
  gather_facts: true
  become: true
  collections:
    - community.general
    - ansible.posix
    - ansible.builtin
  roles:
    - role: lvm_manager
